services:
  # Traefik reverse proxy
  traefik:
    image: traefik:v3.0
    command:
      - "--api.insecure=true"
      - "--providers.docker=true"
      - "--providers.docker.exposedbydefault=false"
      - "--entrypoints.web.address=:80"
    ports:
      - "80:80"
      - "8080:8080"  # Traefik dashboard
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock:ro
      - ./letsencrypt:/letsencrypt
    networks:
      - tinyretro-network
    restart: unless-stopped

  # Backend server (Rust/Axum)
  server:
    build:
      context: ./server
      dockerfile: Dockerfile
    environment:
      - RUST_LOG=debug
    volumes:
      - ./server/retroboard.json:/app/retroboard.json
    networks:
      - tinyretro-network
    restart: unless-stopped
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.server.rule=Host(`localhost`) && (PathPrefix(`/api`) || PathPrefix(`/ws`))"
      - "traefik.http.routers.server.entrypoints=web"
      - "traefik.http.services.server.loadbalancer.server.port=3000"
      # WebSocket support
      - "traefik.http.routers.server.middlewares=websocket-headers"
      - "traefik.http.middlewares.websocket-headers.headers.customrequestheaders.Connection=upgrade"
      - "traefik.http.middlewares.websocket-headers.headers.customrequestheaders.Upgrade=websocket"

  # Frontend client (SvelteKit/Nginx)
  client:
    build:
      context: ./client
      dockerfile: Dockerfile
    networks:
      - tinyretro-network
    restart: unless-stopped
    depends_on:
      - server
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.client.rule=Host(`localhost`)"
      - "traefik.http.routers.client.entrypoints=web"
      - "traefik.http.routers.client.priority=1"
      - "traefik.http.services.client.loadbalancer.server.port=80"

networks:
  tinyretro-network:
    driver: bridge