name: Rust

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

jobs:
  server:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4
      - uses: actions-rust-lang/setup-rust-toolchain@v1
      - name: Lint
        run: make server-lint
      - name: Test
        run: make server-test
      - name: Build
        run: make server-build

  client:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: pnpm/action-setup@v4
        name: Install pnpm
        with:
          version: 10
          run_install: false
      - name: Set up node
        uses: actions/setup-node@v4
        with:
          node-version: 20
          cache: pnpm
          cache-dependency-path: client/pnpm-lock.yaml
      - name: Install dependencies
        run: cd client && pnpm install --frozen-lockfile
      - name: Lint
        run: make client-lint
      - name: Test
        run: make client-test
      - name: Build
        run: make client-build